[package]
name = "nft-pixelboard-io"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.1" }
codec = { package = "parity-scale-codec", version = "3", default-features = false }
scale-info = { version = "2", default-features = false }
